# Generated by Django 2.2.8 on 2020-01-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amigosecretoperson',
            table=None,
        ),
        migrations.AlterModelTable(
            name='amigosecretostate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='disabledcommand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discordingamename',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discorduser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='raidsstate',
            table=None,
        ),
    ]
