# Generated by Django 2.2.8 on 2020-01-31 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20200112_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador_name', models.TextField(max_length=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ammount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.BigIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
