# Generated by Django 2.2.8 on 2020-10-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_doacao_doacaogoal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amigosecretoperson',
            table='amigosecreto',
        ),
        migrations.AlterModelTable(
            name='amigosecretostate',
            table='amigosecretostate',
        ),
        migrations.AlterModelTable(
            name='disabledcommand',
            table='disabled_command',
        ),
        migrations.AlterModelTable(
            name='discordingamename',
            table='ingame_name',
        ),
        migrations.AlterModelTable(
            name='discorduser',
            table='user',
        ),
        migrations.AlterModelTable(
            name='raidsstate',
            table='raidsstate',
        ),
    ]
