# Generated by Django 2.1.5 on 2019-01-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20190110_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(max_length=40, verbose_name='Descrição'),
        ),
    ]
