# Generated by Django 2.1.5 on 2019-01-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20190115_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
    ]
