# Generated by Django 2.1.5 on 2019-01-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=12, verbose_name='Nome')),
                ('exp', models.FloatField()),
                ('rank', models.TextField()),
            ],
        ),
    ]
