# Generated by Django 2.1.5 on 2019-01-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runescape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmember',
            name='rank',
            field=models.TextField(choices=[('Recruit', 'Recruta'), ('Corporal', 'Cabo'), ('Lieutenant', 'Tenente'), ('Captain', 'Capitão'), ('General', 'General'), ('Admin', 'Administrador'), ('Organiser', 'Organizador'), ('Coordinator', 'Coordenador'), ('Overseer', 'Fiscal'), ('Deputy Owner', 'Vice-Líder'), ('Owner', 'Líder')]),
        ),
    ]
