# Generated by Django 2.2.17 on 2024-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runescape', '0002_auto_20190127_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo no Clã'),
        ),
        migrations.AddField(
            model_name='clanmember',
            name='player_name',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='name',
            field=models.TextField(max_length=12, null=True, verbose_name='Nome'),
        ),
    ]
