# Generated by Django 2.1.5 on 2019-01-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20190110_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guia', 'verbose_name_plural': 'Guias'},
        ),
    ]
