# Generated by Django 2.1.4 on 2019-01-05 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25, verbose_name='Título')),
                ('slug', models.SlugField(max_length=35, unique=True)),
                ('category', models.TextField(choices=[('pvm', 'PvM'), ('skilling', 'Habilidades'), ('other', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('description', models.TextField(max_length=50, verbose_name='Descrição')),
                ('content', models.TextField(max_length=5000, verbose_name='Conteúdo')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
