# Generated by Django 2.2.6 on 2019-12-03 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmigoSecretoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.TextField(unique=True, verbose_name='ID Discord')),
                ('discord_name', models.TextField(verbose_name='Nome Discord')),
                ('ingame_name', models.TextField(verbose_name='Nome RuneScape')),
                ('giving_to_id', models.IntegerField(default=None, null=True, unique=True)),
                ('giving_to_name', models.TextField(default=None, null=True, unique=True)),
                ('receiving', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amigosecreto',
            },
        ),
        migrations.CreateModel(
            name='AmigoSecretoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amigosecretostate',
            },
        ),
        migrations.CreateModel(
            name='DisabledCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Nome')),
            ],
            options={
                'db_table': 'disabled_command',
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('warning_date', models.DateField(null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('ingame_name', models.TextField(unique=True)),
                ('discord_id', models.TextField()),
                ('discord_name', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RaidsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(default=False, verbose_name='Notificações')),
                ('time_to_next_message', models.TextField(null=True, verbose_name='Próxima Mensagem')),
            ],
            options={
                'db_table': 'raidsstate',
            },
        ),
        migrations.CreateModel(
            name='DiscordIngameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome RuneScape')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingame_names', to='discord.DiscordUser', verbose_name='Usuário')),
            ],
            options={
                'db_table': 'ingame_name',
            },
        ),
    ]
